/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AnnulationRouteImport } from './routes/annulation'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConseillerRouteImport } from './routes/conseiller'
import { Route as DevenirHoteRouteImport } from './routes/devenir-hote'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MesAnnoncesRouteImport } from './routes/mes-annonces'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as LogementIdRouteImport } from './routes/logement.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnulationRoute = AnnulationRouteImport.update({
  id: '/annulation',
  path: '/annulation',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseillerRoute = ConseillerRouteImport.update({
  id: '/conseiller',
  path: '/conseiller',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirHoteRoute = DevenirHoteRouteImport.update({
  id: '/devenir-hote',
  path: '/devenir-hote',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MesAnnoncesRoute = MesAnnoncesRouteImport.update({
  id: '/mes-annonces',
  path: '/mes-annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const LogementIdRoute = LogementIdRouteImport.update({
  id: '/logement/$id',
  path: '/logement/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aide': typeof AideRoute
  '/annulation': typeof AnnulationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/conseiller': typeof ConseillerRoute
  '/devenir-hote': typeof DevenirHoteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/recherche': typeof RechercheRoute
  '/logement/$id': typeof LogementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aide': typeof AideRoute
  '/annulation': typeof AnnulationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/conseiller': typeof ConseillerRoute
  '/devenir-hote': typeof DevenirHoteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/recherche': typeof RechercheRoute
  '/logement/$id': typeof LogementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aide': typeof AideRoute
  '/annulation': typeof AnnulationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/conseiller': typeof ConseillerRoute
  '/devenir-hote': typeof DevenirHoteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mes-annonces': typeof MesAnnoncesRoute
  '/recherche': typeof RechercheRoute
  '/logement/$id': typeof LogementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aide'
    | '/annulation'
    | '/cgu'
    | '/confidentialite'
    | '/conseiller'
    | '/devenir-hote'
    | '/mentions-legales'
    | '/mes-annonces'
    | '/recherche'
    | '/logement/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aide'
    | '/annulation'
    | '/cgu'
    | '/confidentialite'
    | '/conseiller'
    | '/devenir-hote'
    | '/mentions-legales'
    | '/mes-annonces'
    | '/recherche'
    | '/logement/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aide'
    | '/annulation'
    | '/cgu'
    | '/confidentialite'
    | '/conseiller'
    | '/devenir-hote'
    | '/mentions-legales'
    | '/mes-annonces'
    | '/recherche'
    | '/logement/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AideRoute: typeof AideRoute
  AnnulationRoute: typeof AnnulationRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConseillerRoute: typeof ConseillerRoute
  DevenirHoteRoute: typeof DevenirHoteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MesAnnoncesRoute: typeof MesAnnoncesRoute
  RechercheRoute: typeof RechercheRoute
  LogementIdRoute: typeof LogementIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annulation': {
      id: '/annulation'
      path: '/annulation'
      fullPath: '/annulation'
      preLoaderRoute: typeof AnnulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseiller': {
      id: '/conseiller'
      path: '/conseiller'
      fullPath: '/conseiller'
      preLoaderRoute: typeof ConseillerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-hote': {
      id: '/devenir-hote'
      path: '/devenir-hote'
      fullPath: '/devenir-hote'
      preLoaderRoute: typeof DevenirHoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-annonces': {
      id: '/mes-annonces'
      path: '/mes-annonces'
      fullPath: '/mes-annonces'
      preLoaderRoute: typeof MesAnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logement/$id': {
      id: '/logement/$id'
      path: '/logement/$id'
      fullPath: '/logement/$id'
      preLoaderRoute: typeof LogementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AideRoute: AideRoute,
  AnnulationRoute: AnnulationRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConseillerRoute: ConseillerRoute,
  DevenirHoteRoute: DevenirHoteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MesAnnoncesRoute: MesAnnoncesRoute,
  RechercheRoute: RechercheRoute,
  LogementIdRoute: LogementIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
